const express = require('express')
const app = express()
const morgan = require('morgan')

app.use(morgan('dev'))

app.get('/', (req, res, next) => {
  // I'm going to interrupt requests for index.html 😼
  res.send('hello')
})

app.use(express.static('public'))
// app.use((req, res, next) => {
//   const file = fs.read('./public/' + req.url)
//   if (!file) res.sendStatus(404)
//   else res.send(file)
// })

app.listen(3000, () => {
  console.log('Listening on 3000')
})

/**
 * server.js
 * public/
 *   index.html
 *   style.css
 *   bundle.js <- generated by Webpack
 *   images/
 *     logo.png
 *     banner.jpeg
 */

/* GET localhost:3000/ -> public/index.html */
/* GET localhost:3000/images/logo.png -> public/images/logo.png */
